application: klaudcelet
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: (.*\.html)

# - url: /WeatherSPA
#   static_files: weathers/app/index.html
#   upload: weathers/app/(.*\.html)

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /classes/.*
  script: classes/initDB.php

- url: /classes/.*
  script: classes/DBClass.php

- url: /classes/.*
  script: classes/DBHelper.php

- url: /classes/.*
  script: classes/provider.php

- url: /classes/.*
  script: classes/providerRepository.php

- url: /classes/.*
  script: classes/services.php

- url: /services/.*
  script: services/getProviders.php

- url: /services/.*
  script: services/getProvider.php

- url: /services/.*
  script: services/getServices.php


- url: /js/lib
  static_dir: js/lib

- url: /js/Directives
  static_dir: js/Directives

- url: /images
  static_dir: images

- url: /partials
  static_dir: partials

- url: /db
  static_dir: db
